services:
  # =========================
  # COURSE SERVICE
  # =========================
  course-service:
    build: ./course-service
    container_name: course_service_app
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course-postgres:5432/course_db
      SPRING_DATASOURCE_USERNAME: course_user
      SPRING_DATASOURCE_PASSWORD: course_pass
    depends_on:
      - course-postgres
      - instructor-service
      - student-service
    networks:
      - campus_net

  course-postgres:
    image: postgres:15
    container_name: course_postgres
    environment:
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_pass
      POSTGRES_DB: course_db
    ports:
      - "5434:5432"
    volumes:
      - course_pg_data:/var/lib/postgresql/data
    networks:
      - campus_net

  # =========================
  # INSTRUCTOR SERVICE
  # =========================
  instructor-service:
    build: ./instructor-service
    container_name: instructor_service_app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://instructor-postgres:5432/instructor_db
      SPRING_DATASOURCE_USERNAME: instructor_user
      SPRING_DATASOURCE_PASSWORD: instructor_pass
    depends_on:
      - instructor-postgres
    networks:
      - campus_net

  instructor-postgres:
    image: postgres:15
    container_name: instructor_postgres
    environment:
      POSTGRES_USER: instructor_user
      POSTGRES_PASSWORD: instructor_pass
      POSTGRES_DB: instructor_db
    ports:
      - "5433:5432"
    volumes:
      - instructor_pg_data:/var/lib/postgresql/data
    networks:
      - campus_net

  # =========================
  # STUDENT SERVICE
  # =========================
  student-service:
    build: ./student-service
    container_name: student_service_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://student-postgres:5432/student_db
      SPRING_DATASOURCE_USERNAME: student_user
      SPRING_DATASOURCE_PASSWORD: student_pass
    depends_on:
      - student-postgres
    networks:
      - campus_net

  student-postgres:
    image: postgres:15
    container_name: student_postgres
    environment:
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: student_pass
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - student_pg_data:/var/lib/postgresql/data
    networks:
      - campus_net

# =========================
# VOLUMES
# =========================
volumes:
  course_pg_data:
  instructor_pg_data:
  student_pg_data:

# =========================
# NETWORKS
# =========================
networks:
  campus_net:
    driver: bridge
